---
title: Getting started - Requirements
jupyter: python3
---

Python (🐍):  This assumes that you have a python environment installed.

To install FPsim, you first need to clone or download a copy of the source code from https://github.com/fpsim/fpsim
 
```
git clone -b <branch> --single-branch https://github.com/fpsim/fpsim.git
cd fpsim
pip install -e .
```

If it worked, you should be able to import fpsim with `import fpsim as fp`.


# Getting started with FPsim

The basic design philosophy of FPsim is: **common modelling tasks should be simple**. For example:

- Defining parameters
- Running a simulation
- Plotting results

This tutorial walks you through how to define parameters and run the simulation. The next tutorial will show you how to plot the results of a simulation.

To create, run, and plot a sim with default options is just:

```{python}
import fpsim as fp

sim = fp.Sim(location='kenya')
sim.run()
fig = sim.plot()
```

# Defining parameters

Parameters are defined as a dictionary.
In FPsim, we categorize our parameters as:

* Basic parameters <br> 
* Age limits <br>
* Demographics (urban/rural, wealth)<br>
* Durations<br>
* Pregnancy outcomes<br>
* Fecundity and exposure<br>
* Contraceptive use<br>
* Education <br>

The most common category of parameters to change in FPsim is the basic category, which includes the  geographic location (i.e. Kenya, Senegal, northern India), the starting population, the starting year, and the initial number of agents. We can define these as: 

```{python}
pars = dict(
    n_agents   = 10_000,
    location   = 'kenya',
    start_year = 2000, 
    end_year   = 2020,
)
```

# Running simulations
Running a simulation is pretty easy. In fact, running a sim with the parameters we defined above is just:

```{python}
sim = fp.Sim(pars)
sim.run()
```

# Inspecting results

Running the simulation will generate a results [dictionary] `sim.results`. A dictionary is simply collection of items, and you can access the values of results using different 'key' words. Almost all of the results relevant for FPsim are stored under the key 'fp'; for example, the number of pregnancies over time can be found using `sim.results.fp['pregnancies']`. Execute the code below:

```{python}
sim.results.fp['pregnancies']
```

If you want to see all the 'keys' that are available in the results dictionary you can use

```{python}
sim.list_available_results()
```

# Slightly different way of defining parameters
You can also specify different parameters by specifyuing them directly as arguments in the simulation object:

```{python}
sim = fp.Sim(n_agents=10e3, location='kenya', start_year=2000, end_year=2020)
sim.run()
```

You can mix and match too – pass in the parameter dictionary (`pars` defined above) with some default options, and then include other parameters as arguments to the sim. Doing this overrides the equally named parameters in `pars` because (keyword) arguments take precedence). For example:

```{python}
sim = fp.Sim(pars, n_agents=100) # Use parameters defined above, but overrides the value `n_agents` in pars, and uses instead 100 agents, not 10,000
sim.run()
```

Now you know how to run a basic simulation in FPsim and change the parameters. Now let's take a look at the output of the sim.

# Explore plotting options for a single simulation

Let's take a look at the basic suite of plotting options, once we've run our initial simulation.

The basic plot function will plot births, deaths, and mcpr over the entire simulation.

There are also pre-defined options that combine similar types of output. For instance, 'apo' stands for adverse pregnancy outcomes, and will plot infant deaths, stillbirths, and abortions.

plot() will take any of the following options:

* <i>'cpr'</i> will plot three different ways to define contraceptive prevalence - mCPR, CPR (includes traditional), and aCPR (includes traditional and restricts denominator to sexually active non-pregnant women) <br>
* <i>'apo'</i> will plot adverse pregnancy outcomes, including abortion and miscarriage <br>
* <i>'mortality'</i> will plot mortality-related outcomes <br>
* <i>'method'</i> plots the method mix over time  <br>

```{python}
sim.plot() # the default
sim.plot('cpr')
```

In the next tutorial, we will look at some of the new features of FPsim 2.0, including how to define different contraceptive choice options.

