from . import kenya
from . import senegal
from . import cotedivoire
from . import niger
from . import nigeria_kano
from . import nigeria_kaduna
from . import nigeria_lagos
from . import pakistan_sindh
from . import ethiopia
from .ethiopia.regions import addis_ababa
from .ethiopia.regions import afar
from .ethiopia.regions import amhara
from .ethiopia.regions import benishangul_gumuz
from .ethiopia.regions import dire_dawa
from .ethiopia.regions import gambela
from .ethiopia.regions import harari
from .ethiopia.regions import oromia
from .ethiopia.regions import snnpr
from .ethiopia.regions import somali
from .ethiopia.regions import tigray
