from .kenya_data import kenya
from .senegal_data import senegal
from .cotedivoire_data import cotedivoire
from .niger_data import niger
from .nigeria_kano_data import nigeria_kano
from .nigeria_kaduna_data import nigeria_kaduna
from .nigeria_lagos_data import nigeria_lagos
from .pakistan_sindh_data import pakistan_sindh
from .ethiopia_data import ethiopia
from .ethiopia_data.regions import addis_ababa
from .ethiopia_data.regions import afar
from .ethiopia_data.regions import amhara
from .ethiopia_data.regions import benishangul_gumuz
from .ethiopia_data.regions import dire_dawa
from .ethiopia_data.regions import gambela
from .ethiopia_data.regions import harari
from .ethiopia_data.regions import oromia
from .ethiopia_data.regions import snnpr
from .ethiopia_data.regions import somali
from .ethiopia_data.regions import tigray
